[STYLE] fixup for new year and minor codestyle warnings ( - WIP #48 - )
Changes in file .circleci/config.yml:
 jobs:
 version: 2

Changes in file .github/tool_shlock_helper.sh:
 if [[ $# -gt "$MINPARAMS" ]] ; then

Changes in file Makefile:
 + minor update support for install case

Changes in file README.md:
 + Changed the copyright yeat

Changes in file multicast/__main__.py:
 + simplified readability

Changes in file requirements.txt:
 + minor change for new year

Changes in file setup.cfg:
 + minor update for new year

Changes in file tests/*.py:
 + minor update for year

diff --git a/tests/check_cc_lines b/tests/check_cc_lines
--- a/tests/check_cc_lines
+++ b/tests/check_cc_lines
@@ -102,7 +102,7 @@ if [[ -d ./.git ]] ; then
 elif [[ -d ./tests ]] ; then
 	_TEST_ROOT_DIR=$(pwd) ;
 else
-	echo "FAIL: missing valid folder or file"
+	echo "FAIL: missing valid folder or file" >&2 ;
 	EXIT_CODE=1
 fi
 
