[TESTING] minor fix for check_cc_lines found in review (- WIP PR #384 -)
 * this work is part of #256

Changes in file tests/check_cc_lines:
 * minor fix

diff --git a/tests/check_cc_lines b/tests/check_cc_lines
--- a/tests/check_cc_lines
+++ b/tests/check_cc_lines
@@ -64,24 +64,26 @@ ulimit -t 600
 PATH="/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
 umask 137
 
-LOCK_FILE="${TMPDIR:-/tmp}/cc_line_test_script_lock"
+# tests/check_cc_lines.sh
+readonly SCRIPT_NAME="${0##*/}"
+LOCK_FILE="${TMPDIR:-/tmp}/org.pak.multicast.copyright-lines-shell"
 EXIT_CODE=1
 
 # Function to check if a command exists.
 
 # USAGE:
-#  ~$ check_command CMD
+#	~$ check_command CMD
 # Arguments:
-# CMD (Required) -- Name of the command to check
+#	CMD (Required) -- Name of the command to check
 # Results:
-#    exits 64 -- missing required argument
-#    exits 126 -- check complete and has failed, can not find given command.
-#    returns successful -- check complete and command found to be executable.
+#	exits 64 -- missing required argument
+#	exits 126 -- check complete and has failed, can not find given command.
+#	returns successful -- check complete and command found to be executable.
 function check_command() {
-    test -z "$1" && { printf "%s\n" "Error: command name is required to check for existence." >&2 ; exit 64 ; } ;
-    local cmd="$1" ;
-    # shellcheck disable=SC2086
-    test -x "$(command -v ${cmd})" || { printf "%s\n" "Error: Required command '$cmd' is not found." >&2 ; exit 126 ; } ;
+	test -z "$1" && { printf "%s\n" "Error: command name is required to check for existence." >&2 ; exit 64 ; } ;
+	local cmd="$1" ;
+	# shellcheck disable=SC2086
+	test -x "$(command -v ${cmd})" || { printf "%s\n" "Error: Required command '$cmd' is not found." >&2 ; exit 126 ; } ;
 }  # end check_command()
 # propagate/export function to sub-shells
 export -f check_command
@@ -94,17 +96,24 @@ check_command grep ;
 check_command curl ;
 check_command find ;
 check_command git ;
+check_command sort ;
+check_command tail ;
 check_command python3 ;
 check_command shlock ;
 
-
+# USAGE:
+#	~$ cleanup
+# Arguments:
+#	N/A
+# Results:
+#	returns -- once cleanup has been done on a best-effort case.
 function cleanup() {
 	# shellcheck disable=SC2317
-	rm -f "${LOCK_FILE}" 2>/dev/null || true ;
+	rm -f "${LOCK_FILE}" 2>/dev/null || : ;
 	# shellcheck disable=SC2317
 	wait ;
 	# shellcheck disable=SC2317
-	hash -d shlock 2>/dev/null > /dev/null || true ;
+	hash -d shlock 2>/dev/null > /dev/null || : ;
 }
 
 if [[ ( $(shlock -f "${LOCK_FILE}" -p $$ ) -eq 0 ) ]] ; then
@@ -170,7 +179,7 @@ unset _TEST_ROOT_DIR 2>/dev/null || true ;
 unset _TEST_DOC 2>/dev/null || true ;
 unset _TEST_YEAR 2>/dev/null || true ;
 
-rm -f "${LOCK_FILE}" 2>/dev/null > /dev/null || true ; wait ;
+cleanup || rm -f "${LOCK_FILE}" 2>/dev/null > /dev/null || : ; wait ;
 
 # shellcheck disable=SC2086
 exit ${EXIT_CODE:-255} ;
