[PATCH] Implemented groundwork for #191.
Changes in file tests/check_pip:
 - refactored navigate_git_dir logic

diff --git a/tests/check_pip b/tests/check_pip
--- a/tests/check_pip
+++ b/tests/check_pip
@@ -257,11 +257,17 @@ function navigate_dirs_by_git() {
 	if _TEST_ROOT_DIR=$(git rev-parse --show-superproject-working-tree 2>/dev/null); then
 		if [ -z "${_TEST_ROOT_DIR}" ]; then
 			_TEST_ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null)
+			if [ -z "${_TEST_ROOT_DIR}" ]; then
+				printf "::error file=${SCRIPT_FILE},line=${BASH_LINENO:-0},title=${FUNCNAME:-$0}::%s\n" "FAIL: Could not determine repository root" >&2
+				EXIT_CODE=40
+				return ${EXIT_CODE}
+			fi
 		fi
 		printf "::debug::%s\n" "Found ${_TEST_ROOT_DIR} ..." ;
 	else
 		printf "::error file=${SCRIPT_FILE},line=${BASH_LINENO:-0},title=${FUNCNAME:-$0}::%s\n" "FAIL: missing valid repository or source structure" >&2
 		EXIT_CODE=40
+		return ${EXIT_CODE}
 	fi
 }
 
