[UPGRADE] fixed spellcheck tool (- WIP #111 -)
Changes in file tests/check_spelling:
 * Overhauled as per #111 :tada:

diff --git a/tests/check_spelling b/tests/check_spelling
--- a/tests/check_spelling
+++ b/tests/check_spelling
@@ -59,45 +59,124 @@
 #    the amount of five dollars ($5.00). The foregoing limitations will apply
 #    even if the above stated remedy fails of its essential purpose.
 ################################################################################
+#
+# This script attempts to enforce spell-checking if the codespell tool is available.
+# It accomplishes the following tasks:
+# 1. Sets up error handling and cleanup mechanisms to ensure proper execution.
+# 2. Determines the test root directory based on the project structure.
+# 3. lint and check spelling
+# 4. cleanup and report
+#
+# Usage Summary:
+# To lint the project without making changes:
+# ./tests/check_spelling
+# To lint and auto-correct spelling errors:
+# ./tests/check_spelling --fix
+#
+# Exit Code Summary:
+# The script uses the EXIT_CODE variable to track exit conditions:
+# -   0: Successful execution.
+# -   1: General failure.
+# -   2: Coverage combine or XML generation failed.
+# -   3: git ls-tree command failed.
+# -  40: Missing valid repository or source structure.
+# - 126: Script already in progress or command not executable.
+# - 129: Received SIGHUP signal.
+# - 130: Received SIGINT signal (Ctrl+C).
+# - 131: Received SIGQUIT signal.
+# - 137: Received SIGABRT signal.
+# - 143: Received SIGTERM signal.
+#
+# The primary goal is to allow linter like spell-checking.
 
 ulimit -t 600
-PATH="/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
+# setting the path may break brain-dead CI that uses crazy paths
+# PATH="/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
 umask 137
 
-LOCK_FILE="${TMPDIR:-/tmp}/spelling_test_script_lock"
+# force utf-8 for spelling
+export LC_CTYPE="${LC_CTYPE:-'en_US.UTF-8'}"
+
+LOCK_FILE="${TMPDIR:-/tmp}/org.pak.multicast.spell-check-shell"
 EXIT_CODE=1
 
-# exit fast if command is missing
-test -x /usr/bin/spellintian || exit 126 ;
+test -x $(command -v grep) || exit 126 ;
+test -x $(command -v python3) || exit 126 ;
+test -x $(command -v git) || exit 126 ;
+hash -p ./.github/tool_shlock_helper.sh shlock || exit 255 ;
+test -x "$(command -v shlock)" || exit 126 ;
+test -x $(command -v codespell) || exit 126 ;
+
+# Set codespell options
+CODESPELL_OPTIONS="--quiet-level=4 --builtin clear,rare,code -L assertIn"
+
+function cleanup() {
+	rm -f ${LOCK_FILE} 2>/dev/null || : ; wait ;
+	# unset when done
+	unset LOCK_FILE 2>/dev/null || : ;
+	hash -d shlock 2>/dev/null || : ;
+}
 
 if [[ ( $(shlock -f ${LOCK_FILE} -p $$ ) -eq 0 ) ]] ; then
 		EXIT_CODE=0
-		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || true ; wait ; exit 129 ;' SIGHUP || EXIT_CODE=129
-		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || true ; wait ; exit 143 ;' SIGTERM || EXIT_CODE=143
-		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || true ; wait ; exit 131 ;' SIGQUIT || EXIT_CODE=131
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 129 ;' SIGHUP || EXIT_CODE=129
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 143 ;' SIGTERM || EXIT_CODE=143
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 131 ;' SIGQUIT || EXIT_CODE=131
 		# SC2173 - https://github.com/koalaman/shellcheck/wiki/SC2173
-		#trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || true ; wait ; exit 1 ;' SIGSTOP || EXIT_CODE=7
-		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || true ; wait ; exit 130 ;' SIGINT || EXIT_CODE=130
-		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || true || true ; wait ; exit 137 ;' SIGABRT || EXIT_CODE=137
-		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || true ; wait ; exit ${EXIT_CODE} ;' EXIT || EXIT_CODE=1
+		#trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 1 ;' SIGSTOP || EXIT_CODE=7
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 130 ;' SIGINT || EXIT_CODE=130
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true || true ; wait ; exit 137 ;' SIGABRT || EXIT_CODE=137
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit ${EXIT_CODE} ;' EXIT || EXIT_CODE=1
 else
-        echo Test already in progress by `head ${LOCK_FILE}` ;
-        false ;
-        exit 126 ;
+		# shellcheck disable=SC2046
+		printf "\t%s\n" "Check Setup Scripts Tests Coverage already in progress by "$(head "${LOCK_FILE}") >&2 ;
+		exit 126 ;
+fi
+
+# this is how test files are found:
+
+# THIS IS THE ACTUAL TEST
+_TEST_ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null) ;
+if [[ -d ../.git ]] ; then
+	_TEST_ROOT_DIR="../" ;
+elif [[ -d ./.git ]] ; then
+	_TEST_ROOT_DIR=$(pwd) ;
+elif [[ ( -d $(git rev-parse --show-toplevel 2>/dev/null) ) ]] ; then
+	_TEST_ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null) ;
+else
+	printf "\t%s\n" "FAIL: missing valid repository or source structure" >&2 ;
+	EXIT_CODE=40
+fi
+
+# Get a list of files to check using git ls-tree with filtering
+FILES_TO_CHECK=$(git ls-tree -r --full-tree --name-only HEAD -- *.md *.py *.txt **/*.md **/*.txt **/*.py 2>/dev/null || EXIT_CODE=3)
+
+# Enable auto-correction if '--fix' argument is provided
+if [[ "$1" == "--fix" ]]; then
+	CODESPELL_OPTIONS="--write-changes --interactive 2 ${CODESPELL_OPTIONS}"
+	printf "%s\n" "Auto-correction enabled."
 fi
 
 # THIS IS THE ACTUAL TEST
-THE_TEMP_FILE="/tmp/swapfile_spellcheck_${RANDOM}.tmp.txt" ;
-( (spellintian "${@:-./**/*}" 2>/dev/null | fgrep -v "(duplicate word)" | fgrep " -> ") & (spellintian "${@:-./*}" 2>/dev/null | fgrep -v "(duplicate word)" | fgrep " -> ") & (spellintian "${@:-./**/**/*}"  2>/dev/null | fgrep -v "(duplicate word)" | fgrep " -> ") ) | sort -h | uniq | tee -a ${THE_TEMP_FILE:-/dev/null} ;
-wait ;
-THECOUNT=$( (wc -l ${THE_TEMP_FILE} 2>/dev/null || echo 0) | cut -d\  -f 1 ) ;
-EXIT_CODE=${THECOUNT} ;
-if [[ ("${THECOUNT}" -le 1) ]] ; then
-	EXIT_CODE=0 ;
-	echo "OK: Found no detected spelling errors." ;
+# Iterate over files and run codespell
+for FILE in $FILES_TO_CHECK; do
+	printf "%s\n" "Checking ${FILE}" ;
+	{ codespell $CODESPELL_OPTIONS "${FILE}" || EXIT_CODE=$? ;} 2>/dev/null ; wait ;
+done
+
+# cleaning up and reporting
+
+if [[ ("${EXIT_CODE}" -eq 0) ]] ; then
+	printf "%s\n" "OK: Found no detected spelling errors." ;
 else
-	echo "FAIL: Found ${THECOUNT:-many} spelling errors." ;
+	printf "%s\n" "FAIL: Found spelling errors." ;
 fi
-rm -f ${THE_TEMP_FILE} 2>/dev/null >> /dev/null || true ;
+
+cleanup || rm -f ${LOCK_FILE} 2>/dev/null || : ;
+
+# unset when done
+unset _TEST_ROOT_DIR 2>/dev/null || : ;
+unset CODESPELL_OPTIONS 2>/dev/null || : ;
+
 wait ;
 exit ${EXIT_CODE:255} ;
