[PATCH] apply changes from review (- WIP #118 -)
### ChangeLog:

Changes in file .github/workflows/Tests.yml:
 jobs:

Changes in file tests/check_pip:
 Unknown Changes

diff --git a/tests/check_pip b/tests/check_pip
--- a/tests/check_pip
+++ b/tests/check_pip
@@ -60,6 +60,7 @@
 #    even if the above stated remedy fails of its essential purpose.
 ################################################################################
 #
+# check_pip: Audit and validate Python requirements files.
 # This, best-effort, script audits and validates Python requirements files using tools like pip-audit and pip-licenses.
 # It accomplishes the following tasks:
 # 1. Sets up a safe execution environment with resource limits and UTF-8 encoding.
@@ -81,6 +82,7 @@
 # -   3: git ls-tree command failed.
 # -   4: pip-audit failed.
 # -   5: pip-licenses failed.
+# -   6: pip install/unistall failed.
 # -  40: Missing valid repository or source structure.
 # - 126: Script already in progress or command not executable.
 # - 129: Received SIGHUP signal.
@@ -89,30 +91,30 @@
 # - 137: Received SIGABRT signal.
 # - 143: Received SIGTERM signal.
 
+# Try to safely setup and fail fast if unable.
 ulimit -t 600
 # setting the path may break brain-dead CI that uses crazy paths
 # PATH="/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
 umask 137
 
-# force utf-8 for spelling
+# force utf-8 for checking in script
 export LC_CTYPE="${LC_CTYPE:-en_US.UTF-8}"
-
+# set remaining variables
 LOCK_FILE="${TMPDIR:-/tmp}/org.pak.multicast.pip-check-shell"
-EXIT_CODE=1
-
+# fail fast if missing something
 test -x $(command -v grep) || exit 126 ;
 test -x $(command -v python3) || exit 126 ;
 test -x $(command -v git) || exit 126 ;
+test -x $(command -v pip) || exit 126 ;
+test -x $(command -v pip-audit) || exit 126 ;  # optional tool
+test -x $(command -v pip-licenses) || exit 126 ;
 hash -p ./.github/tool_shlock_helper.sh shlock || exit 255 ;
 test -x "$(command -v shlock)" || exit 126 ;
-test -x $(command -v pip-audit) || exit 126 ;
-test -x $(command -v pip-licenses) || exit 126 ;
 
-# Set pip-audit options
-AUDIT_OPTIONS="--progress-spinner off --desc on --requirement"
+# Set default exitcode to failure until sure we won't need to abort
+EXIT_CODE=1
 
-# Set pip-licenses options
-LICENSE_OPTIONS="--from=mixed"
+# end of bootstraping, use functions below this point
 
 function cleanup() {
 	rm -f ${LOCK_FILE} 2>/dev/null || : ; wait ;
@@ -121,7 +123,8 @@ function cleanup() {
 	hash -d shlock 2>/dev/null || : ;
 }
 
-if [[ ( $(shlock -f ${LOCK_FILE} -p $$ ) -eq 0 ) ]] ; then
+function handle_signals() {
+	if [[ ( $(shlock -f ${LOCK_FILE} -p $$ ) -eq 0 ) ]] ; then
 		EXIT_CODE=0
 		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 129 ;' SIGHUP || EXIT_CODE=129
 		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 143 ;' SIGTERM || EXIT_CODE=143
@@ -129,69 +132,101 @@ if [[ ( $(shlock -f ${LOCK_FILE} -p $$ ) -eq 0 ) ]] ; then
 		# SC2173 - https://github.com/koalaman/shellcheck/wiki/SC2173
 		#trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 1 ;' SIGSTOP || EXIT_CODE=7
 		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 130 ;' SIGINT || EXIT_CODE=130
-		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true || true ; wait ; exit 137 ;' SIGABRT || EXIT_CODE=137
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 137 ;' SIGABRT || EXIT_CODE=137
 		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit ${EXIT_CODE} ;' EXIT || EXIT_CODE=1
-else
+	else
 		# shellcheck disable=SC2046
 		printf "\t%s\n" "Check Setup Scripts Tests Coverage already in progress by "$(head "${LOCK_FILE}") >&2 ;
 		exit 126 ;
+	fi
+}
+
+handle_signals
+
+# lazy defined variables should be defined now that this is the only script instance.
+
+# Set pip-audit options
+AUDIT_OPTIONS="--progress-spinner off --desc on --requirement"
+# List of Allowed Licenses delimited by semicolon ;
+ALLOW_LICENSES="Public Domain;Apache Software License;MIT License;BSD License;Python Software Foundation License"
+# Set pip-licenses options
+LICENSE_OPTIONS="--from=mixed"
+
+# Enable auto-fix if '--fix' argument is provided
+if [[ "$1" == "--fix" ]]; then
+	AUDIT_OPTIONS="--fix --strict ${AUDIT_OPTIONS}"
+	printf "%s\n" "Auto-fix enabled."
 fi
 
-# check_pip: Audit and validate Python requirements files.
+# lazy defined functions should be defined now that this is the only script instance.
+
+function report_summary() {
+	# Improved reporting based on EXIT_CODE
+	case "${EXIT_CODE}" in
+		0) printf "%s\n" "OK: Found no detected requirements errors." ;;
+		1) printf "%s\n" "FAIL: General failure during script execution." >&2 ;;
+		3) printf "%s\n" "FAIL: Gathering repostory's requirements failed." >&2 ;;  # git ls-tree command failed
+		4) printf "%s\n" "FAIL: pip-audit detected security vulnerabilities." >&2 ;;
+		5) printf "%s\n" "FAIL: pip-licenses detected license issues." >&2 ;;
+		6) printf "%s\n" "FAIL: pip install failed." >&2 ;;
+		126) printf "%s\n" "SKIP: Unable to continue script execution." >&2 ;;
+		*) printf "%s\n" "FAIL: Detected requirements errors." >&2 ;;
+	esac
+}
+
+function navigate_dirs_by_git() {
+	if [[ -d ../.git ]] ; then
+		_TEST_ROOT_DIR="../" ;
+	elif [[ -d ./.git ]] ; then
+		_TEST_ROOT_DIR=$(pwd) ;
+	elif [[ ( -d $(git rev-parse --show-toplevel 2>/dev/null) ) ]] ; then
+		_TEST_ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null) ;
+	else
+		printf "\t%s\n" "FAIL: missing valid repository or source structure" >&2 ;
+		EXIT_CODE=40
+	fi
+}
 
 # THIS IS THE ACTUAL TEST DIR USED (update _TEST_ROOT_DIR as needed)
 _TEST_ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null) ;
-if [[ -d ../.git ]] ; then
-	_TEST_ROOT_DIR="../" ;
-elif [[ -d ./.git ]] ; then
-	_TEST_ROOT_DIR=$(pwd) ;
-elif [[ ( -d $(git rev-parse --show-toplevel 2>/dev/null) ) ]] ; then
-	_TEST_ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null) ;
-else
-	printf "\t%s\n" "FAIL: missing valid repository or source structure" >&2 ;
-	EXIT_CODE=40
-fi
+navigate_dirs_by_git
 
-cd $_TEST_ROOT_DIR 2>/dev/null || EXIT_CODE=40
-
-# Get a list of files to check using git ls-tree with filtering
-FILES_TO_CHECK=$(git ls-tree -r --full-tree --name-only HEAD -- **/requirements.txt *-requirements.txt requirements.txt 2>/dev/null || EXIT_CODE=3)
-
-# Enable auto-correction if '--fix' argument is provided
-if [[ "$1" == "--fix" ]]; then
-	AUDIT_OPTIONS="--fix --strict ${AUDIT_OPTIONS}"
-	printf "%s\n" "Auto-correction enabled."
-fi
+# Get a list of files to check using git ls-tree with filtering (and careful shell globing)
+FILES_TO_CHECK=$(git ls-tree -r --full-tree --name-only HEAD -- "${_TEST_ROOT_DIR}"/**/requirements.txt "${_TEST_ROOT_DIR}"/*-requirements.txt "${_TEST_ROOT_DIR}/requirements.txt" 2>/dev/null || EXIT_CODE=3)
 
 # THIS IS THE ACTUAL TEST
 # Iterate over files and run checks
 for req_file in $FILES_TO_CHECK; do
-	printf "%s\n" "Checking ${req_file}" ;
-	printf "%s\n" "Auditing ${req_file} for security vulnerabilities..."
-	{ pip-audit $AUDIT_OPTIONS "${req_file}" || EXIT_CODE=4 ;} ; wait ;
+	printf "\t%s\n" "Checking ${req_file}" ;
+	if [[ ( -x $(command -v pip-audit) ) ]] && [[ ("${EXIT_CODE}" -eq 0) ]] ; then
+		printf "\t\t%s\n" "Auditing ${req_file} for security vulnerabilities..."
+		{ pip-audit $AUDIT_OPTIONS "${req_file}" || EXIT_CODE=4 ;} ; wait ;
+	fi ;
 	if [[ ("${EXIT_CODE}" -eq 0) ]] ; then
-		printf "%s\n" "Checking licenses in $req_file..." ;
-		{ pip install -r "$req_file" --quiet >/dev/null || EXIT_CODE=4 ;} 2>/dev/null ; wait ;
-		{ pip-licenses $LICENSE_OPTIONS || EXIT_CODE=5 ;} 2>/dev/null ; wait ;
+		printf "\t\t%s\n" "Checking licenses in $req_file..." ;
+		if [[ ( $(pip install -r "$req_file" --quiet 2>&1 >/dev/null || false) ) ]] ; then
+			{ pip-licenses $LICENSE_OPTIONS --allow-only="${ALLOW_LICENSES}" || EXIT_CODE=5 ;} ; wait ;
+		else
+			[[ ("${EXIT_CODE}" -eq 0) ]] && EXIT_CODE=6
+			printf "\t%s\n" "FAIL: pip install failed for $req_file." >&2
+		fi
 	else
-		printf "%s\n" "FAIL: Found requirements errors." >&2 ;
+		printf "\t%s\n" "FAIL: Found requirements errors." >&2 ;
 	fi
 done
 
-# cleaning up and reporting
+# summary reporting
+report_summary
 
-if [[ ("${EXIT_CODE}" -eq 0) ]] ; then
-	printf "%s\n" "OK: Found no detected requirements errors." ;
-else
-	printf "%s\n" "FAIL: Found requirements errors." >&2 ;
-fi
-
+# cleaning up
 cleanup || rm -f ${LOCK_FILE} 2>/dev/null || : ;
 
 # unset when done
 unset _TEST_ROOT_DIR 2>/dev/null || : ;
 unset AUDIT_OPTIONS 2>/dev/null || : ;
+unset ALLOW_LICENSES 2>/dev/null || : ;
 unset LICENSE_OPTIONS 2>/dev/null || : ;
 
 wait ;
+# Exit with the appropriate code
 exit ${EXIT_CODE:-255} ;
