[PATCH] fixes for integration testing script (- WIP #55 -)
Changes in file tests/check_integration_coverage:
 - fixed usage of multicast cli
 - new random port diognostics
 - some clarification comments added

diff --git a/tests/check_integration_coverage b/tests/check_integration_coverage
--- a/tests/check_integration_coverage
+++ b/tests/check_integration_coverage
@@ -65,22 +65,24 @@ ulimit -t 60
 # PATH="/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
 umask 137
 
-
+# exported Env vars
 export LC_CTYPE="${LC_CTYPE:-'en_US.UTF-8'}"
 
-LOCK_FILE="${TMPDIR:-/tmp}/org.pak.multicast.cov-integration-shell"
-EXIT_CODE=1
-
+# dependencies
 test -x $(command -v grep) || exit 126 ;
 test -x $(command -v python3) || exit 126 ;
 test -x $(command -v git) || exit 126 ;
-hash -p ./.github/tool_shlock_helper.sh shlock || exit 255 ;
-test -x "$(command -v shlock)" || exit 126 ;
 test -x $(command -v make) || exit 126 ;
 test -x $(command -v tee) || exit 126 ;
+# CEP-5 locking
+hash -p ./.github/tool_shlock_helper.sh shlock || exit 255 ;
+test -x "$(command -v shlock)" || exit 126 ;
 
+# rest of the script vars
 LOG_FILE="test_log_${PPID}.log"
 ERR_FILE="test_log_errors_${PPID}.log"
+LOCK_FILE="${TMPDIR:-/tmp}/org.pak.multicast.cov-integration-shell"
+EXIT_CODE=1
 
 function cleanup() {
 	rm -f ./${LOG_FILE} 2>/dev/null || true ; wait ;
@@ -104,9 +106,9 @@ else
 		exit 126 ;
 fi
 
-# this is how test files are found:
+# setup test fixtures
 
-# THIS IS THE ACTUAL TEST
+# this is how test files are found:
 if _TEST_ROOT_DIR=$(git rev-parse --show-superproject-working-tree 2>/dev/null); then
 	if [ -z "${_TEST_ROOT_DIR}" ]; then
 		_TEST_ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null)
@@ -120,11 +122,13 @@ TEST_MCAST_PORT=$(((RANDOM % 16384) + 49152));
 TEST_MCAST_GROUP='224.0.0.1' ;
 export COVERAGE_CMD="$(command -v python3) -m coverage run --source=multicast -p -m"
 
+# start test-suite
+
 make -j1 -f Makefile test-reports || EXIT_CODE=3 ;
 printf "%s\n\n" "Start of Log:" > ./${LOG_FILE} ; wait ;
 printf "%s\n\n" "Will use host-port: [${TEST_MCAST_GROUP} : ${TEST_MCAST_PORT}]" >> ./${LOG_FILE} ; wait ;
 printf "%s\n\n" "Start of Integration Test one-shot:" >> ./${LOG_FILE} ; wait ;
-( sleep 1 ; ${COVERAGE_CMD} multicast RECV --use-std --port ${TEST_MCAST_PORT} --group ${TEST_MCAST_GROUP} --groups ${TEST_MCAST_GROUP} 2>./${ERR_FILE} & sleep 6 ; kill -9 $! 2>/dev/null ) >> ./${LOG_FILE} & true ;
+( sleep 1 ; ${COVERAGE_CMD} multicast --use-std RECV --port ${TEST_MCAST_PORT} --groups ${TEST_MCAST_GROUP} --group ${TEST_MCAST_GROUP} 2>./${ERR_FILE} & sleep 6 ; kill -9 $! 2>/dev/null ) >> ./${LOG_FILE} & true ;
 
 for PCOUNT in $(seq 1 5) ; do
 	${COVERAGE_CMD} multicast SAY --port ${TEST_MCAST_PORT} --group ${TEST_MCAST_GROUP} --message "TEST from $PCOUNT" 2>/dev/null & sleep 1 ;
@@ -145,6 +149,8 @@ ${COVERAGE_CMD} multicast SAY --port ${TEST_MCAST_PORT} --group ${TEST_MCAST_GRO
 ${COVERAGE_CMD} multicast SAY --port ${TEST_MCAST_PORT} --group ${TEST_MCAST_GROUP} --message "STOP" 2>/dev/null ;
 wait ;
 printf "%s\n\n" "End of Integration Test daemon" >> ./${LOG_FILE} ; wait ;
+
+# cleanup from test-suite
 
 $(command -v python3) -m coverage combine 2>/dev/null || EXIT_CODE=2 ;
 $(command -v python3) -m coverage xml --include=multicast/* -o ./test-reports/coverage_supplement.xml || EXIT_CODE=2 ;
