[PATCH] Apply suggestions from code review
Co-authored-by: coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>

diff --git a/tests/check_pip b/tests/check_pip
--- a/tests/check_pip
+++ b/tests/check_pip
@@ -214,7 +214,7 @@ function navigate_dirs_by_git() {
 		fi
 		printf "::debug::%s\n" "Found ${_TEST_ROOT_DIR} ..." ;
 	else
-		printf "::error file=file=${SCRIPT_FILE},line=${BASH_LINENO:-0},title=${FUNCNAME:-$0}::%s\n" "FAIL: missing valid repository or source structure" >&2
+		printf "::error file=${SCRIPT_FILE},line=${BASH_LINENO:-0},title=${FUNCNAME:-$0}::%s\n" "FAIL: missing valid repository or source structure" >&2
 		EXIT_CODE=40
 	fi
 }
@@ -263,7 +263,7 @@ function check_license_when_given_req() {
 	deactivate
 
 	# return to starting dir
-	cd ${OLD_PWD} ;
+	cd "${OLDPWD}" ;
 
 	# Remove the temporary directory and all of its contents
 	rm -rf "$temp_dir"
