[COVERAGE] add additional coverage testing for legacy build system (- WIP #46 & #49 & #50 -)
Changes in file .github/workflows/Tests.yml:
 - added extra tests for legacy build system as part of EOL and coverage support

Changes in file Makefile:
 - minor changes to conform with other changes

Changes in file pyproject.toml:
 update for new build system

Changes in file tests/check_integration_coverage:
 improved performance and stability

Changes in file tests/check_legacy_setup_coverage:
 new test case for legacy build system (setup.py)

diff --git a/tests/check_legacy_setup_coverage b/tests/check_legacy_setup_coverage
--- a/tests/check_legacy_setup_coverage
+++ b/tests/check_legacy_setup_coverage
@@ -65,10 +65,9 @@ ulimit -t 60
 # PATH="/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
 umask 137
 
-
 export LC_CTYPE="${LC_CTYPE:-'en_US.UTF-8'}"
 
-LOCK_FILE="${TMPDIR:-/tmp}/org.pak.multicast.cov-integration-shell"
+LOCK_FILE="${TMPDIR:-/tmp}/org.pak.multicast.cov-legacy-setup-shell"
 EXIT_CODE=1
 
 test -x $(command -v grep) || exit 126 ;
@@ -83,9 +82,9 @@ LOG_FILE="test_log_${PPID}.log"
 ERR_FILE="test_log_errors_${PPID}.log"
 
 function cleanup() {
-	rm -f ./${LOG_FILE} 2>/dev/null || true ; wait ;
-	rm -f ./${ERR_FILE} 2>/dev/null || true ; wait ;
-	rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ;
+	rm -f ./${LOG_FILE} 2>/dev/null || : ;
+	rm -f ./${ERR_FILE} 2>/dev/null || : ;
+	rm -f ${LOCK_FILE} 2>/dev/null || : ; wait ;
 	hash -d shlock 2>/dev/null > /dev/null || true ;
 }
 
@@ -100,7 +99,7 @@ if [[ ( $(shlock -f ${LOCK_FILE} -p $$ ) -eq 0 ) ]] ; then
 		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || true || true ; wait ; exit 137 ;' SIGABRT || EXIT_CODE=137
 		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || true ; wait ; exit ${EXIT_CODE} ;' EXIT || EXIT_CODE=1
 else
-		printf "%s\n" "Check Integration Tests Coverage already in progress by "`head ${LOCK_FILE}` ;
+		printf "%s\n" "Check Setup Scripts Tests Coverage already in progress by "`head ${LOCK_FILE}` ;
 		exit 126 ;
 fi
 
@@ -117,55 +116,33 @@ else
 	EXIT_CODE=1
 fi
 
-TEST_MCAST_PORT=59595;
-TEST_MCAST_GROUP='224.0.0.1' ;
-export COVERAGE_CMD="$(command -v python3) -m coverage run --source=multicast -p -m"
+export COVERAGE_CMD="$(command -v python3) -m coverage run --include=setup.py -p"
 
 make -j1 -f Makefile test-reports || EXIT_CODE=3 ;
 printf "%s\n" "Start of Log:" > ./${LOG_FILE} ; wait ;
 printf "%s\n" "" >> ./${LOG_FILE} ; wait ;
-printf "%s\n" "Start of Integration Test one-shot:" >> ./${LOG_FILE} ; wait ;
-printf "%s\n" "" >> ./${LOG_FILE} ; wait ;
-( sleep 1 ; ${COVERAGE_CMD} multicast RECV --use-std --port ${TEST_MCAST_PORT} --groups ${TEST_MCAST_GROUP} --group ${TEST_MCAST_GROUP} 2>./${ERR_FILE} & sleep 6 ; kill -9 $! 2>/dev/null ) >> ./${LOG_FILE} & true ;
-
-for PCOUNT in $(seq 1 5) ; do
-	${COVERAGE_CMD} multicast SAY --port ${TEST_MCAST_PORT} --mcast-group ${TEST_MCAST_GROUP} --message "TEST from $PCOUNT" 2>/dev/null & sleep 1 ;
-done ;
-
-${COVERAGE_CMD} multicast SAY --port ${TEST_MCAST_PORT} --group ${TEST_MCAST_GROUP} --message "STOP from $TEST_MCAST_GROUP" 2>/dev/null & sleep 1 ;
-${COVERAGE_CMD} multicast SAY --port ${TEST_MCAST_PORT} --group ${TEST_MCAST_GROUP} --message "STOP" 2>/dev/null ;
-printf "%s\n" "End of Integration Test one-shot" >> ./${LOG_FILE} ; wait ;
+printf "%s\n" "Start of Setup.py Test one-shot:" >> ./${LOG_FILE} ; wait ;
 printf "%s\n" "" >> ./${LOG_FILE} ; wait ;
 
-printf "%s\n" "Start of Integration Test deamon:" >> ./${LOG_FILE} ; wait ;
-printf "%s\n" "" >> ./${LOG_FILE} ; wait ;
-( sleep 1 ; ${COVERAGE_CMD} multicast --deamon HEAR --port ${TEST_MCAST_PORT} --group ${TEST_MCAST_GROUP} 2>./${ERR_FILE} & sleep 6 ; kill -9 $! 2>/dev/null ) >> ./${LOG_FILE} & true ;
+{ ${COVERAGE_CMD} ./setup.py --version 2>./${ERR_FILE} | grep --count -oE "^([0-9].){2}[0-9]$" 2>./${ERR_FILE} || echo "FAIL: Setup.py version check failed" 1>&2 ;} 2>./${ERR_FILE} >> ./${LOG_FILE} & true ;
 
-for PCOUNT in $(seq 1 5) ; do
-	${COVERAGE_CMD} multicast SAY --port ${TEST_MCAST_PORT} --group ${TEST_MCAST_GROUP} --message "TEST from $PCOUNT" 2>/dev/null & : ;
-done ;
-
-${COVERAGE_CMD} multicast SAY --port ${TEST_MCAST_PORT} --group ${TEST_MCAST_GROUP} --message "STOP from $TEST_MCAST_GROUP" 2>/dev/null & sleep 1 ;
-${COVERAGE_CMD} multicast SAY --port ${TEST_MCAST_PORT} --group ${TEST_MCAST_GROUP} --message "STOP" 2>/dev/null ;
 wait ;
-printf "%s\n" "End of Integration Test deamon" >> ./${LOG_FILE} ; wait ;
+printf "%s\n" "End of Setup.py Test one-shot" >> ./${LOG_FILE} ; wait ;
 printf "%s\n" "" >> ./${LOG_FILE} ; wait ;
 
 $(command -v python3) -m coverage combine 2>/dev/null || EXIT_CODE=2 ;
-$(command -v python3) -m coverage xml --include=multicast/* -o ./test-reports/coverage_supplement.xml || EXIT_CODE=2 ;
+$(command -v python3) -m coverage xml --include=setup.py,multicast -o ./test-reports/coverage_setup.xml || EXIT_CODE=2 ;
 
 wait ;
-cp -f ./${LOG_FILE} ./test-reports/integration_data_log.log 2>/dev/null ; wait ;
-printf "%s\n" "" | tee -a ./test-reports/integration_data_log.log ; wait ;
+cp -f ./${LOG_FILE} ./test-reports/legacy_setup_version_log.log 2>/dev/null ; wait ;
+printf "%s\n" "" | tee -a ./test-reports/legacy_setup_version_log.log ; wait ;
 
 if [[ ( -r ./${ERR_FILE} ) ]] ; then
-	printf "%s\n" "Errors: " | tee -a ./test-reports/integration_data_log.log ; wait ;
-	cat <./${ERR_FILE} | tee -a ./test-reports/integration_data_log.log ; wait ;
+	printf "%s\n" "Errors: " | tee -a ./test-reports/legacy_setup_version_log.log ; wait ;
+	cat <./${ERR_FILE} | tee -a ./test-reports/legacy_setup_version_log.log ; wait ;
 fi
 
 unset COVERAGE_CMD 2>/dev/null || : ;
-unset TEST_MCAST_GROUP 2>/dev/null || : ;
-unset TEST_MCAST_PORT 2>/dev/null || : ;
 
 cleanup || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || true ; wait ;
 
