[PATCH] Fix for yaml syntax (- WIP #130 -)
Changes in file .github/actions/fetch-test-reporter/action.yml:
 * corrected yaml syntax
 * pivot to use inputs instead of secrets
 * added support for coveralls-token input

Changes in file .github/actions/purge-test-reporter/action.yml:
 * initial implementation

Changes in file .github/tools/fetch-test-reporter:
 * submodule version bump

Changes in file .github/workflows/Tests.yml:
 * related work

Changes in file tests/check_pip:
 * followup from fixing GHI #400
 * refactor ignore options
   * added more ways to allow public domain dependencies
   * ignore "UNKNOWN" result for BSD packages

diff --git a/.github/actions/purge-test-reporter/action.yml b/.github/actions/purge-test-reporter/action.yml
--- a/.github/actions/purge-test-reporter/action.yml
+++ b/.github/actions/purge-test-reporter/action.yml
@@ -1,10 +1,10 @@
 ---
-name: 'Fetch Code Coverage Tools'
-description: 'Fetch various Code Coverage tools'
+name: 'Purge Code Coverage Tools'
+description: 'Purge various Code Coverage tools'
 author: 'Mr. Walls'
 branding:
-  icon: 'download-cloud'
-  color: 'blue'
+  icon: 'delete'
+  color: 'white'
 inputs:
   token:
     description: |
@@ -38,12 +38,12 @@ outputs:
   sha:
     description: "The SHA of the commit checked-out"
     value: ${{ steps.output_sha.outputs.sha || 'HEAD' }}
-  can_fetch:
-    description: "Can the fetch tool even be used?"
-    value: ${{ steps.output_can_fetch.outputs.can_fetch || 'false' }}
+  can_purge:
+    description: "Can the purge tool even be used?"
+    value: ${{ steps.output_can_purge.outputs.can_purge || 'false' }}
   status:
-    description: "The outcome of the fetch test reporter action."
-    value: ${{ steps.fetch_outcome.outputs.status || 'cancelled' }}
+    description: "The outcome of the purge test reporter action."
+    value: ${{ steps.purge_outcome.outputs.status || 'cancelled' }}
 
 runs:
   using: composite
@@ -54,20 +54,20 @@ runs:
       run: |
         printf "sha=%s\n" $(git rev-parse --verify HEAD) >> "$GITHUB_OUTPUT"
         printf "FETCH_SHA=%s\n" $(git rev-parse --verify HEAD) >> "$GITHUB_ENV"
-    - name: "Check has Fetch Tool"
-      id: output_can_fetch
+    - name: "Check has Purge Tool"
+      id: output_can_purge
       shell: bash
       run: |
-        if [[ -x ${{ github.workspace }}/.github/tools/fetch-test-reporter/fetch-test-reporter ]] ; then
-          printf "can_fetch=true\n" >> "$GITHUB_OUTPUT"
-          printf "::debug::%s\n" "Found ${{ github.workspace }}/.github/tools/fetch-test-reporter/fetch-test-reporter"
+        if [[ -x ${{ github.workspace }}/.github/tools/fetch-test-reporter/purge-test-reporter ]] ; then
+          printf "can_purge=true\n" >> "$GITHUB_OUTPUT"
+          printf "::debug::%s\n" "Found ${{ github.workspace }}/.github/tools/fetch-test-reporter/purge-test-reporter"
         else
-          printf "::warning, title='Missing tool':: %s\n" "Can't find fetch-test-reporter tool."
-          printf "can_fetch=false\n" >> "$GITHUB_OUTPUT"
+          printf "::warning, title='Missing tool':: %s\n" "Can't find purge-test-reporter tool."
+          printf "can_purge=false\n" >> "$GITHUB_OUTPUT"
         fi
-    - name: "Install test reporter tools on ${{ runner.os }}"
-      id: fetch-test-reporter-main
-      if: ${{ !cancelled() && (steps.output_can_fetch.outputs.can_fetch == 'true') && (runner.os != 'Windows') && (github.repository == 'reactive-firewall/multicast') }}
+    - name: "Finalize test reporter tools on ${{ runner.os }}"
+      id: purge-test-reporter-main
+      if: ${{ !cancelled() && (steps.output_can_purge.outputs.can_purge == 'true') && (runner.os != 'Windows') && (github.repository == 'reactive-firewall/multicast') }}
       shell: bash
       env:
         CODECLIMATE_REPO_TOKEN: ${{ github.server_url == 'https://github.com' && inputs.codeclimate-token || '' }}
@@ -75,14 +75,14 @@ runs:
         COVERALLS_REPO_TOKEN: ${{ github.server_url == 'https://github.com' && inputs.coveralls-token || '' }}
         DEEPSOURCE_DSN: ${{ github.server_url == 'https://github.com' && inputs.deepsource-dsn || '' }}
       run: |
-        ${{ github.workspace }}/.github/tools/fetch-test-reporter/fetch-test-reporter || exit $?
+        ${{ github.workspace }}/.github/tools/fetch-test-reporter/purge-test-reporter || exit $?
     - name: "Evaluate Fetch Task"
-      id: fetch_outcome
+      id: purge_outcome
       if: ${{ !cancelled() }}
       shell: bash
       run: |
-        if [[ "${{ steps.output_can_fetch.outputs.can_fetch }}" == "true" ]] ; then
-          if [[ "${{ steps.fetch-test-reporter-main.outcome }}" == "success" ]] ; then
+        if [[ "${{ steps.output_can_purge.outputs.can_purge }}" == "true" ]] ; then
+          if [[ "${{ steps.purge-test-reporter-main.outcome }}" == "success" ]] ; then
             THE_RESULT="success"
           else
             THE_RESULT="failure"
