[STYLE] Applied changes as discussed in review (- WIP #227 -)
Changes in file .github/workflows/makefile-lint.yml:
 - Use POSIX-compliant validation
 - Provide more detailed error messages
 - Add debug logging (safely)

Changes in file .github/workflows/markdown-lint.yml:
 - fixed incorect file path
 - Use POSIX-compliant validation
 - Provide more detailed error messages
 - Add debug logging (safely)

diff --git a/.github/workflows/makefile-lint.yml b/.github/workflows/makefile-lint.yml
--- a/.github/workflows/makefile-lint.yml
+++ b/.github/workflows/makefile-lint.yml
@@ -31,12 +31,19 @@ jobs:
       - name: Lint Workflow YAML
         if: ${{ success() }}
         run: |
-          if [[ "${{ vars.YAML_ARGS }}" =~ ^[a-zA-Z0-9\ \-\.]*$ ]]; then
-            yamllint ${{ vars.YAML_ARGS }} .github/workflows/makefile-lint.yml
-          else
-            echo "Invalid YAML_ARGS provided"
-            exit 1
-          fi
+          case "${{ vars.YAML_ARGS }}" in
+            *[!a-zA-Z0-9\ \-\.]*)
+              ERR_MSG_STUB="Invalid YAML_ARGS: contains unauthorized characters"
+              ERR_DETAILS="file=.github/workflows/makefile-lint.yml,line=35,endLine=41,"
+              ERR_TITLE="title=VALIDATION_ERROR"
+              printf "::error %s::ERROR %s\n" "${ERR_DETAILS}${ERR_TITLE}" "${ERR_MSG_STUB}"
+              exit 1
+              ;;
+            *)
+              printf "Validating workflow with args: %s\n" "${YAML_ARGS}"
+              yamllint ${YAML_ARGS} .github/workflows/makefile-lint.yml
+              ;;
+          esac
       - name: Install checkmake
         if: ${{ success() }}
         env:
