[PATCH] Implemented validation logic for #196
Changes in file .github/workflows/makefile-lint.yml:
 - implemented check for validating YAML_ARGS

Changes in file .github/workflows/markdown-lint.yml:
 - implemented check for validating YAML_ARGS

diff --git a/.github/workflows/makefile-lint.yml b/.github/workflows/makefile-lint.yml
--- a/.github/workflows/makefile-lint.yml
+++ b/.github/workflows/makefile-lint.yml
@@ -31,7 +31,12 @@ jobs:
       - name: Lint Workflow YAML
         if: ${{ success() }}
         run: |
-          yamllint ${{ vars.YAML_ARGS }} .github/workflows/makefile-lint.yml
+          if [[ "${{ vars.YAML_ARGS }}" =~ ^[a-zA-Z0-9\ \-\.]*$ ]]; then
+            yamllint ${{ vars.YAML_ARGS }} .github/workflows/makefile-lint.yml
+          else
+            echo "Invalid YAML_ARGS provided"
+            exit 1
+          fi
       - name: Install checkmake
         if: ${{ success() }}
         env:
diff --git a/.github/workflows/markdown-lint.yml b/.github/workflows/markdown-lint.yml
--- a/.github/workflows/markdown-lint.yml
+++ b/.github/workflows/markdown-lint.yml
@@ -31,8 +31,14 @@ jobs:
           yamllint --version || { printf "%s\n" "${ERR_MSG_LINE}"; exit 1; }
 
       - name: Lint Workflow YAML
+        if: ${{ success() }}
         run: |
-          yamllint ${{ vars.YAML_ARGS }} .github/workflows/markdown-lint.yml
+          if [[ "${{ vars.YAML_ARGS }}" =~ ^[a-zA-Z0-9\ \-\.]*$ ]]; then
+            yamllint ${{ vars.YAML_ARGS }} .github/workflows/makefile-lint.yml
+          else
+            printf "%s\n" "Invalid YAML_ARGS provided"
+            exit 1
+          fi
 
       - name: Install NPM Dependencies
         run: |
